name: password_strength
description: A password strength estimator. Can be used to show the user whether the password they chose is strong against bruteforce or dictionary attacks.
version: 0.1.2
homepage: https://github.com/pikaju/password-strength

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: ^1.16.8
